### ISSUE TITLE
Add Montreal city and dockered app ?

### ISSUE THREAD

**Issue by arlion-dev** [evert/communauto-car-notify#2]
Is it possible to add Montreal City ?

Maybe add a Dockerfile from this exemple :

```dockerfile
# Utiliser l'image Fedora 39 comme base
FROM fedora:39

# Installer les dépendances nécessaires
RUN dnf -y update && \
    dnf -y install geoclue2-demos nodejs && \
    dnf clean all

# Créer un répertoire pour l'application
WORKDIR /app

# Copier les fichiers de l'application dans le conteneur
COPY . /app

# Rendre le script exécutable
RUN chmod +x run.mjs

# Exposer le port si nécessaire (à modifier selon les besoins de l'application)
EXPOSE 3000

# Commande par défaut pour lancer l'application
CMD ["./run.mjs", "--city", "montreal"]
```

**Comment by evert** [comment]
Hey! If you can find the branchIds i'll add them! if not ill take a look.

Docker feels a bit silly for this I think. Just a quick script ofr me !

**Comment by arlion-dev** [comment]
Hello !
BranchId seems to be number 1.

Docker is useful for not to have to install all nodejs stuff and be compatible to all distribution or OS solution. 
Seems more complicated to passthrough notification from container to desktop maybe add possibility to switch notification solution to another could be easier to implement but just a suggestion.

Thank you !

**Comment by evert** [comment]
Added montreal @arlion-dev ! Hope it works well for you.

I'm not 100% against having a docker container, but:

* you have to submit it as a PR
* Make sure that the geo-lookup works (I'm somewhat skeptical because the GPS lookup system needs access to wifi network names to get accurate results).
* Allow users to pass parameters somehow so it's not hardcoded to Montreal as per your example
